# Ports collection:     zlib-1.2.7
# Date created:         2011/6/24
# Whom:                 Max Lee <yowching.lee@gmail.com>

PORTNAME 		= zlib
PORTVERSION 		= 1.2.11
CATEGORIES 		= archivers
MASTER_SITES		= http://www.gzip.org/%SUBDIR%/			\
			  http://www.zlib.net/
MASTER_SITE_SUBDIR	= zlib
LICENSE			= zlib

MAINTAINER 		= yowching.lee@gmail.com
COMMENT 		= A Massively Spiffy Yet Delicately Unobrtusive Compression Library.

#
#
#

MASTERDIR 		= $(CURDIR)
PORTSDIR 		= $(MASTERDIR)/../..
include $(PORTSDIR)/Mk/linux.port.mk
