# Ports collection:	automake
# Date created:		8/Feb/2025
# Whom:			Max Lee <yowching.lee@gmail.com>

PORTNAME		= automake
DISTVERSION		= 1.17
CATEGORIES		= devel
MASTER_SITES		= $(MASTER_SITE_GNU)
MASTER_SITE_SUBDIR	= $(PORTNAME)

MAINTAINER		= yowching.lee@gmail.com
COMMENT			= GNU Standard-compliant Makefile generator

LICENSE			= GPLv2+

USES			= tar:xz

GNU_CONFIGURE		= yes

#
#
#

MASTERDIR		= $(CURDIR)
PORTSDIR		?= $(MASTERDIR)/../..
include $(PORTSDIR)/Mk/linux.port.mk
